### ISSUE TITLE
kmdb-ui not working

### ISSUE THREAD

**Issue by jwtd** [HouseTrip/km-db#8]
The web appears to start but is not rendering any pages. When I run the ui command, it looks like a server spins up, but it returns 404's to every request...

```bash
jd:bin jd$ bundle exec kmdb-ui
[2015-04-24 00:15:45] INFO  WEBrick 1.3.1
[2015-04-24 00:15:45] INFO  ruby 2.2.0 (2014-12-25) [x86_64-darwin14]
[2015-04-24 00:15:45] INFO  WEBrick::HTTPServer#start: pid=59055 port=8885
^[[A^[[A^[[A^[[B::1 - - [24/Apr/2015:00:24:39 -0400] "GET / HTTP/1.1" 404 - 0.0007
::1 - - [24/Apr/2015:00:24:40 -0400] "GET /favicon.ico HTTP/1.1" 404 - 0.0006
```

The browser renders this for every request...

```bash
Not Found: /
```

**Comment by mrship** [comment]
`kmdb-ui` just provides a web interface to Resque. If you visit `/resque` you'll see the Resque UI.

**Comment by jwtd** [comment]
Thanks for the reply. Yes, I figured it was a window to the queue. Pulling up "http://localhost:5984/resque" results in:

```
{"error":"not_found","reason":"no_db_file"}
```

**Comment by mrship** [comment]
Per the README, have you set these two ENV vars?

- `DATABASE_URL` (required), e.g. `mysql2://km_db_test@localhost/km_db_test`
- `KMDB_REDIS_URL` [localhost], e.g. `redis://localhost/14`

**Comment by jwtd** [comment]
Yes, I had set those. I was just missing the /resque path in the browser. I suppose not serving the app at the root reduces the chances of a collision when its installed inside an existing rails app. Thanks for your help. The import is working as intended now.
