### ISSUE TITLE
name column's too small for some email addresses

### ISSUE THREAD

**Issue by jwtd** [HouseTrip/km-db#9]
As my import was progressing, I noticed a number of failed jobs in Resque. The vast majority of them are invalid sql errors that occur when the import tries to insert a user's email address that is longer than 48 characters. I changed the limit on all name related columns in [/lib/kmdb/migrations/01_kmdb_initial.rb](https://github.com/HouseTrip/km-db/blob/master/lib/kmdb/migrations/01_kmdb_initial.rb#L42) from 48 to 100 to resolve.

**Comment by mottalrd** [comment]
Hi @jwtd thank you for the feedback! I will close the issue for the moment since you got it fixed. Will update the migration to have more space
